version: '3.8'
services:
  equation_solver_service:
    build:
      context: ./equation_solver_service
      dockerfile: Dockerfile
    command: >
      sh -c "export PYTHONPATH=/app && python /app/equation_solver_service/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=equation_solver_service.settings

  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    command: >
      sh -c "export PYTHONPATH=/app && python /app/user_service/manage.py runserver 0.0.0.0:8002"
    ports:
      - 8002:8002
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=user_service.settings

  db:
    image: postgres
    environment:
      POSTGRES_DB: mathbuddy
      POSTGRES_USER: userone
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-h", "localhost", "-U", "mathbuddy"]
      timeout: 10s
      retries: 5
  
  test:
    build:
      context: ./equation_solver_service
      dockerfile: Dockerfile
    command: >
      sh -c "export PYTHONPATH=/app && python /app/equation_solver_service/manage.py test api.tests --keepdb"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=equation_solver_service.settings

volumes:
  dbdata:
